---
- name: Create internet
  hosts: node3
  vars_files:
    - ./vars.yml
  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ pkgs }}"    
    - name: Configure service
      service:
        {name: "{{ item }}", state: started, enabled: yes} 
      loop: "{{ web_srv }}"    
    - name: Configure firewalld with http
      firewalld:
        {service: http, state: enabled, permanent: yes, immediate: yes}
